name: Mirror Dev to Prod

on:
  workflow_dispatch: # manual trigger
  # Uncomment below if you want auto-sync whenever dev changes
  # repository_dispatch:
  #   types: [sync-to-prod]

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Prod Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Dev Remote
        run: |
          git remote add dev https://github.com/Haider-Ali077/aura-business-command-center.git
          git fetch dev

      - name: Mirror Dev → Prod
        run: |
          git checkout main
          git reset --hard dev/main
          git push origin main --force
