name: Promote to Prod

on:
  workflow_dispatch: # Manual trigger from Actions tab

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Dev Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get full history

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Push to Prod Repo
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote add prod https://Haider-Ali077:${GH_PAT}@github.com/Haider-Ali077/Intelllyca_frontend_prod.git
          git push prod HEAD:main --force-with-lease


